import 'package:dro_health/model/product_model.dart';

List<ProductList> listProducts = [
  ProductList(productName: "Panadol",soldPic:"Emzor_Pharmaceuticals" ,soldBy: "Emzor Pharmaceuticals",isPrescribed: true,productImage:"Panadol",productId: "PRO558252791",amount: 100.00,description: "1 pack of Emzor Panadol (500mg) contains 8 units of 12 tablets",liked: false,numberTablet: 12,dosePack: 8,packSize: 96,tabletMg: "500mg",constituent: "PANADOL",dispenseIn: "Packs"),
  ProductList(productName: "Doliprane",soldPic:"Nabco_Pharmaceuticals",soldBy: "Nabco Pharmaceuticals",isPrescribed: true,productImage:"Doliprane",productId: "PRO558252792",amount: 150.00,description: "1 pack of Emzor Doliprane (200mg) contains 8 units of 12 tablets",liked: false,numberTablet: 12,dosePack: 8,packSize: 96,tabletMg: "200mg",constituent: "DOPLIPRANE",dispenseIn: "Packs"),

  ProductList(productName: "Paracetamol",soldPic:"Kings_Pharmaceuticals",soldBy: "Kings Pharmaceuticals",isPrescribed: true,productImage:"Paracetamol-400",productId: "PRO558252793",amount: 200.00,description: "1 pack of Emzor Paracetamol (400mg) contains 8 units of 12 tablets",liked: false,numberTablet: 12,dosePack: 8,packSize: 96,tabletMg: "400mg",constituent: "PARACETAMOL",dispenseIn: "Packs"),
  ProductList(productName: "Ibuprofen",soldPic:"Sonotech_Pharmaceuticals",soldBy: "Sonotech Pharmaceuticals",isPrescribed: false,productImage:"Ibuprofen-200",productId: "PRO558252794",amount: 150.00,description: "1 pack of Emzor Ibuprofen (200mg) contains 8 units of 12 tablets",liked: false,numberTablet: 12,dosePack: 8,packSize: 96,tabletMg: "200mg",constituent: "IBUPROFEN",dispenseIn: "Packs"),
  ProductList(productName: "Ibuprofen",soldPic:"Lancete_Pharmaceuticals",soldBy: "Lancete Pharmaceuticals",isPrescribed: true,productImage:"Ibuprofen-400",productId: "PRO558252795",amount: 300.00,description: "1 pack of Emzor Ibuprofen (400mg) contains 8 units of 12 tablets",liked: false,numberTablet: 12,dosePack: 8,packSize: 96,tabletMg: "400mg",constituent: "IBUPROFEN",dispenseIn: "Packs"),
  ProductList(productName: "Paracetamol",soldPic:"MediLab_Pharmaceuticals",soldBy: "MediLab Pharmaceuticals",isPrescribed: true,productImage:"Paracetamol-200",productId: "PRO558252796",amount: 400.00,description: "1 pack of Emzor Paracetamol (200mg) contains 8 units of 12 tablets",liked: false,numberTablet: 12,dosePack: 8,packSize: 96,tabletMg: "200mg",constituent: "PARACETAMOL",dispenseIn: "Packs"),];
